apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  labels:
    camel.apache.org/kamelet.type: "sink"
    camel.apache.org/kamelet.name: "log"
    camel.apache.org/kamelet.version: "v1alpha1"
spec:
  definition:
    title: "Logger"
    description: "Logger"
    properties:
      loggerName:
        title: Name of the logging category
        description:  Name of the logging category
        type: string
        default: "logger"
      showAll:
        title: Show All
        description: Show All
        type: boolean
        default: false
      multiLine:
        title: Multi Line
        description: Multi Line
        type: boolean
        default: false
  dependencies:
    - "camel:log"
  flow:
    from:
      uri: "kamelet:source"
      steps:
        - to:
            uri: "log"
            properties:
              loggerName: "{{loggerName}}"
              showAll: "{{showAll}}"
              multiline: "{{multiLine}}"
